name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Test Compile ${{ matrix.compiler }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.compiler }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        compiler: [clang, gcc]

    steps:
      - uses: actions/checkout@v2.1.1

      - name: Configure build
        run: cmake -Bbuild -DWARNINGS_AS_ERRORS=ON .

      - name: Build
        working-directory: build
        run: make

      - name: binding-functions
        working-directory: build
        run: |
          make binding-functions
          test -s binding-functions

      - name: Tests
        working-directory: build
        run: |
          make test
          sudo make install

      - name: Test packaging
        working-directory: build
        if: startsWith(matrix.os, 'ubuntu')
        run: cpack -D CPACK_PACKAGE_CONTACT="Test build in CI"

      - name: Examples
        run: |
          mkdir build/examples
          cd build/examples
          cmake ../../examples
          make
          make test
